
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };
