// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xadvdyaffgkzvjbzuipq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZHZkeWFmZmdrenZqYnp1aXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTYxMzQsImV4cCI6MjA1NzE3MjEzNH0.Z6Of-C02wJFpJbsUQF8qLbs0puY19txi6wI7MfH2phU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);